server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    banner-mode: 'OFF'
  thymeleaf:
    check-template-location: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

graph:
  path: ${GRAPH_PATH:C:\Users\wallyson\Desktop\bexs\graph.csv}